### ISSUE TITLE
Do you have any OCR model to try?

### ISSUE THREAD

**Issue by threefoldo** [neuralmagic/sparsezoo#133]
**Is your feature request related to a problem? Please describe.**
We want to run a small CRNN or DBNet OCR on CPU, running on Windows.

**Describe the solution you'd like**
a pretrained model, or detailed introduction of how to build by our own.

**Describe alternatives you've considered**
train a model for us.

**Additional context**
it will be a component in RPA product which automate daily tasks.

**Comment by jeanniefinks** [comment]
Hi @threefoldo 
We saw that you also posted this inquiry to our Deep Sparse Community Slack. I wanted to re-post our answer here for others to see in case they may have similar interests. We'll most likely continue the conversation in Slack!
Cheers, Jeannie / Neural Magic

Neural Magic has not tried to optimize any OCR models yet. Happy to help walk you through the process and support as we can, though. The first step will be integrating your training pipeline with SparseML. High-level instructions can be found in the [SparseML readme](https://github.com/neuralmagic/sparseml#quick-tour) and let us know if you have any questions. Additionally, are you working with any open-source code? If so, we can potentially help do that integration.

After that, you'll need to create a recipe that will handle the sparsification process. We have a few tools that will help along with this. Once you're ready, let us know and we can get you up and running with those.
