### ISSUE TITLE
is there any support for yolov4-mish model ? 

### ISSUE THREAD

**Issue by akashAD98** [neuralmagic/sparsezoo#153]
I'm using this repo for object detection https://github.com/AlexeyAB/darknet
,there are very good models which has a good map on coco,  so is there any way to support this model?

also i have a few questions about neuralmagic

1. lets say if i trained model using any framework   (im using **alexyab darknet**-yolov4-mish model), can i use model weights & apply your techniques to get sparsemodel?
2.  if i converted my model into onnx ,can i  able to use your libraries furture? to get high fps on cpu?
3. also lots of confusion in documents .not able to understand from where should we start? bcz there are similar names such as 
SparseML, Sparsify, DeepSparse .

**Comment by akashAD98** [comment]
@KSGulin thanks it's an open-source project  ? is there any blog / youtube video that explains how to do pruning & quantization for cv-cnn-object detection model? what are the top keys we need to consider while doing pruning & quantization.

**Comment by KSGulin** [comment]
@akashAD98 yes, all the libraries mentioned are open-source. The engine is the one component which we have not open sourced.
