### ISSUE TITLE
OpenAI whisper model sparsed

### ISSUE THREAD

**Issue by manuelsh** [neuralmagic/sparsezoo#249]
**Describe the solution you'd like**
Would like to understand if the Whisper model, which currently is part of the Transformer library of Hugging Phase, is part of your roadmap, and if so, when are you planning to have it as part of the sparse models.

Thanks.

**Comment by jeanniefinks** [comment]
Hi @manuelsh 
Thank you for your inquiry on Whisper. It is on our longer-term roadmap. While we don't have a timetable at this time, I encourage you to [join our Community Slack](https://join.slack.com/t/discuss-neuralmagic/shared_invite/zt-q1a1cnvo-YBoICSIw3L1dmQpjBeDurQ) if not already and share a general use. It will help support awareness and real-life application for these types of model requests!
Regards,
Jeannie @ Neural Magic
