### ISSUE TITLE
Can the table show speed and model size comparasion before and after sparse/>?

### ISSUE THREAD

**Issue by jinfagang** [neuralmagic/sparsezoo#250]
Hello, from the table I can not saw any gains from sparse.

At least it would be very intuitive if the model size and speed were compared.

**Comment by NMfitz** [comment]
Hi jinfagang I am "Fitz" the UX lead at Neural Magic. Thank you for your suggestion! Two quick questions:
a) Where do you want to see such a comparison - on the homepage list of models or an individual model page?
b) Would you want to see metrics of both models (e.g "model one ### itm/sec" and "sparse model one ### itm/sec") or a callout like "sparse model one x-times faster"?)

**Comment by jeanniefinks** [comment]
@jinfagang for awareness/notification, thanks.
