### ISSUE TITLE
deepsparse support for numpy > 1.21.6 ?

### ISSUE THREAD

**Issue by SmartAudioTools** [neuralmagic/sparsezoo#336]
Hello, 
I would like to be able to use deepsparse with a numpy > 1.21.6 . Is it just a setup.py problem or is there a real incompatibility with numpy > 1.21.6 ?
thanks

**Comment by dbogunowicz** [comment]
Hey @SmartAudioTools . Yes, there is a bit of a problem with the fact that newer numpy versions when creating ragged nested sequences. We are currently working on the solution as we speak and in a matter of days, we should be supporting the latest numpy version.

**Comment by rahul-tuli** [comment]
Hi @SmartAudioTools latest Numpy support landed on nightly yesterday!You could try that.
