### ISSUE TITLE
 numpy>=1.22 support

### ISSUE THREAD

**Issue by SmartAudioTools** [neuralmagic/sparsezoo#343]
Hello!
I'm still not able to install deepsparse with numpy>=1.22 with pip install. 
The pipy version does not seem to include the modification.

ERROR: Cannot install deepsparse and numpy>=1.22 because these package versions have conflicting dependencies.

The conflict is caused by:
The user requested numpy>=1.22
deepsparse 1.5.2 depends on numpy>=1.16.3
onnx 1.12.0 depends on numpy>=1.16.6
sparsezoo 1.5.2 depends on numpy<=1.21.6 and >=1.0.0

**Comment by bfineran** [comment]
Hi @SmartAudioTools support for the latest numpy versions was added as part of our work towards our 1.6 release which will be cut soon. In the meantime, you can access the latest code with `sparsezoo-nightly`

**Comment by jeanniefinks** [comment]
Hello @SmartAudioTools 
Release 1.6 had gone out; [release notes are here](https://github.com/neuralmagic/sparseml/releases/tag/v1.6.0). 
I am going to ahead and close out this issue. Feel free to re-open if you have additional questions.
Thank you! Regards,
Jeannie / Neural Magic
