### ISSUE TITLE
Adding new/custom models

### ISSUE THREAD

**Issue by fcakyon** [neuralmagic/sparsezoo#38]
Hello, thanks a lot for this useful framework.

How can I add new models to the modelzoo? Assume I want to perform sparse optimized inference on yolov5: I train a yolov5 model, I convert it to ONNX format, then what?

I looked over the docs but couldnt find the details on this.

**Comment by markurtz** [comment]
Hi fcakyon, thank you for the interest and request! The models must be in a specific format that includes the native framework files, ONNX conversion, sample inputs and outputs, and the recipe or repeatable instructions for how the model was created.

Once the model folder is in a good state, we can add it to the zoo. Currently, it is a little more complicated to add models, but in the future, we'll have support for a UI to upload model contributions through. To add the model for now, we support emailing the folder to support@neuralmagic.com. After this, we'll add it to our deployment backend to make sure it is pushed up!

We'll work to get a new document created to specify the exact format needed as well as general instructions for creating them. I'll be sure to update this issue with that pull request once it's up.

**Comment by jeanniefinks** [comment]
Hello @fcakyon 
Small update here: As we have restructured our product roadmap, we're looking at about 2-3 months before we release a UI to allow models to be uploaded. In the meantime, please check out our alpha website (!) [https://sparsezoo.neuralmagic.com ](https://sparsezoo.neuralmagic.com ) - we welcome feedback.  If there are wishlist features you think would be great to consider, talk 'em up in either the nm-sparsezoo Slack channel ([https://neuralmagic.com/community](https://neuralmagic.com/community)) or [file a GitHub Feature Request Issue](https://github.com/neuralmagic/sparsezoo/issues/new?assignees=&labels=enhancement&template=feature_request.md).

Thank you!
Jeannie - Neural Magic

**Comment by jeanniefinks** [comment]
I'll close this issue out for now but it can be re-opened if there is more follow-up.
Thank you!
Jeannie - Neural Magic
