### ISSUE TITLE
Reproduction problem

### ISSUE THREAD

**Issue by H-cool** [neuralmagic/sparsezoo#481]
Hello, I am reproducing the llama2-7b-gsm8k_llama2_pretrain-pruned60_quantized model. When fine-tuning the llama2 model without pruning, do you use the file https://github.com/IST-DASLab/SparseFinetuning/blob/main/scripts/train/train.py to fine-tune, specifically? How are the parameters selected? Thank you very much for your answer.

**Comment by mgoin** [comment]
Hey @H-cool we have a guide for reproducing Llama 2 7B GSM8k sparse finetuning results using SparseML, please check it out here! https://docs.neuralmagic.com/llms/guides/sparse-finetuning-llm-gsm8k-with-sparseml
